import * as store from '@/store'
import db from '@/db'
import tripsRepo from '@/db/repositories/trips'
import plansRepo from '@/db/repositories/plans'
import segmentsRepo from '@/db/repositories/segments'
import {
    generateSlug,
    createSyntheticDownload,
    getRandomUnsplashImageUrl,
} from '@/lib/utils'
import dayjs from 'dayjs'
import { toast } from 'sonner'

export const backupTrip = async trip => {
    
    const segments = await segmentsRepo.table
        .where('tripId')
        .equals(trip.id)
        .sortBy('startDate')
    
    const data = {
        type: 'single',
        trip,
        segments,
    }
    
    const date = dayjs().format('YYYY-MM-DD_HH-mm-ss')
    const jsonData = JSON.stringify(data, null, 4)
    const fileType = 'application/json'
    const fileName = `${generateSlug(trip.name)}-${date}.json`
    
    createSyntheticDownload(jsonData, fileType, fileName)
    
}

export const backupAllTrips = async () => {
    
    const trips = await tripsRepo.getAll()
    const segments = await segmentsRepo.getAll()
    
    const data = {
        type: 'multiple',
        trips,
        segments,
    }
    
    const date = dayjs().format('YYYY-MM-DD_HH-mm-ss')
    const jsonData = JSON.stringify(data, null, 4)
    const fileType = 'application/json'
    const fileName = `trips-${date}.json`
    
    createSyntheticDownload(jsonData, fileType, fileName)
    
}

// @todo was working but now with Dexie cloud, need to handle IDs
export const restoreTrip1 = async (data, overwrite = false) => {
    
    if (data.type !== 'single')
        throw new Error('Invalid backup type')
    
    const { trip, segments } = data
    
    store.importTripStatus.setValue(`Importing Trip: ${trip.name}`)
    store.importTripProgressMax.setValue(segments.length + 1)
    store.importTripProgressValue.setValue(0)
    
    console.log('restoreTrip: restoring trip', trip.name, 'with', segments.length, 'segments')
    
    let shouldDeleteTrip = false
    
    const existingTrip = await tripsRepo.getById(trip.id)
    
    if (existingTrip)
        if (!overwrite)
            throw new Error('Trip already exists')
        else
            shouldDeleteTrip = true
    
    const existingSegments = await Promise.all(segments.map(it => segmentsRepo.getById(it.id)))
    
    if (existingSegments.length > 0)
        if (!overwrite)
            throw new Error('Some segments already exist')
    
    if (shouldDeleteTrip)
        await tripsRepo.delete(trip.id)
    
    // Extra check, but deleting the trip should have also deleted all related segments
    if (existingSegments.length > 0)
        await Promise.all(existingSegments
            .filter(it => Boolean(it?.id))
            .map(it => segmentsRepo.delete(it.id)))
    
    if (!trip.coverImageUrl)
        trip.coverImageUrl = await getRandomUnsplashImageUrl(trip.name)
    
    console.log('actions#restoreTrip creating trip')
    await tripsRepo.create(trip)
    store.importTripProgressValue.setValue(1)
    
    console.log('actions#restoreTrip creating segments')
    await Promise.all(segments.map(async it => {
        await segmentsRepo.create(it)
        store.importTripProgressValue.setValue(
            store.importTripProgressValue.getValue() + 1)
    }))
    
}

export const restoreTrip = async (data, onConflictAction = 'duplicate') => {
    
    return console.warn('need to implement plans restore')
    
    console.log('restoreTrip', { onConflictAction })
    
    if (data.type !== 'single')
        throw new Error('Invalid backup type')
    
    const { trip, segments } = data
    
    const existingTrip = await tripsRepo.getById(trip.id) || await tripsRepo.getByName(trip.name, true)
    const existingSegments = await Promise.all(segments.map(it => segmentsRepo.getById(it.id)))
    
    if (existingTrip?.id && onConflictAction === 'duplicate') {
        
        delete trip.id
        delete data.trip.id
        
        trip.name = `${trip.name} (Copy ${dayjs().format('YYYY-MMM-DD')})`
        data.trip.name = trip.name
        
        for (let i = 0; i < segments.length; i++) {
            
            // Auto generated by the database
            delete segments[i].id
            delete data.segments[i].id
            
            // Assigned after new trip is created
            delete segments[i].tripId
            delete data.segments[i].tripId
            
        }
        
    }
    
    // @todo @debug
    const overwrite = onConflictAction === 'overwrite'
    
    store.importTripStatus.setValue(`Importing Trip: ${trip.name}`)
    store.importTripProgressMax.setValue(segments.length + 1)
    store.importTripProgressValue.setValue(0)
    
    console.log('restoreTrip: restoring trip', trip.name, 'with', segments.length, 'segments')
    
    if (existingTrip && overwrite)
        await tripsRepo.delete(trip.id)
    
    // Extra check, but deleting the trip should have also deleted all related segments
    if (existingSegments.length > 0 && overwrite)
        await Promise.all(existingSegments
            .filter(it => Boolean(it?.id))
            .map(it => segmentsRepo.delete(it.id)))
    
    if (!trip.coverImageUrl)
        trip.coverImageUrl = await getRandomUnsplashImageUrl(trip.name)
    
    const dbgAllTrips = await tripsRepo.getAll()
    const dbgAllSegments = await segmentsRepo.getAll()
    
    if (overwrite) {
        await Promise.all(dbgAllSegments.map(it => segmentsRepo.delete(it.id)))
        await Promise.all(dbgAllTrips.map(it => tripsRepo.delete(it.id)))
    }
    
    console.log('actions#restoreTrip creating trip', {
        dbgAllTrips,
        dbgAllSegments,
    })
    
    delete trip.id
    
    const newTripId = await tripsRepo.create(trip)
    
    store.importTripProgressValue.setValue(1)
    
    segments.forEach((_, i) => {
        delete segments[i].id
        segments[i].tripId = newTripId
    })
    
    console.log('actions#restoreTrip creating segments')
    await Promise.all(segments.map(async it => {
        await segmentsRepo.create(it)
        store.importTripProgressValue.setValue(
            store.importTripProgressValue.getValue() + 1)
    }))
    
}

export const restoreAllTrips = async (data, onConflictAction = 'duplicate') => {
    
    if (data.type !== 'multiple')
        throw new Error('Invalid backup type')
    
    const promises = data.trips.map(trip => {
        
        const segments = data.segments.filter(seg => seg.tripId === trip.id)
        
        return restoreTrip({
            type: 'single',
            trip,
            segments,
        }, onConflictAction)
        
    })
    
    await Promise.all(promises)
    
}

export const updateSegmentWithCascade = async (currentTrip, planId, segmentId, field, value) => {
    
    const segments = await segmentsRepo.table
        .where('planId')
        .equals(planId)
        // .reverse()
        .sortBy('startDate')
    
    const segmentIndex = segments.findIndex(s => s.id === segmentId)
    
    if (segmentIndex === -1) {
        console.error('Segment not found for update:', segmentId)
        toast.error('Segment not found')
        return
    }
    
    // If the field is not a date, perform a simple update
    if (field !== 'startDate' && field !== 'endDate') {
        
        try {
            await segmentsRepo.update(segmentId, { [field]: value })
            console.log('updateSegment segment updated', segmentId, 'field', field, 'value', value)
            toast('Segment updated')
        } catch (error) {
            console.error('Failed to update segment field:', error)
            toast.error('Failed to update segment')
        }
        
        return
        
    }
    
    // --- Handle Date Updates and Cascade ---
    try {
        
        await db.transaction('rw', db.segments, async () => {
            
            const updates = [] // Array to hold updates for bulkPut
            let currentSegment = segments[segmentIndex]
            let previousEndDate = null
            
            // 1. Calculate changes for the target segment
            let newStartDateStr, newEndDateStr
            const originalDurationDays = dayjs(currentSegment.endDate)
                .diff(dayjs(currentSegment.startDate), 'day')
            
            if (field === 'startDate') {
                newStartDateStr = dayjs(value).toISOString()
                newEndDateStr = dayjs(value).add(originalDurationDays, 'day').toISOString()
            } else { // field === 'endDate'
                newStartDateStr = dayjs(currentSegment.startDate).toISOString() // Keep original start date
                newEndDateStr = dayjs(value).toISOString()
                // Optional: Recalculate duration if endDate is manually changed and you want
                // subsequent segments to respect *that*
                // const newDurationDays = dayjs(newEndDateStr).diff(dayjs(newStartDateStr), 'day');
                // If duration must be preserved, the logic above for startDate change is sufficient.
                // If end date change *can* alter duration, use newDurationDays below.
                // For now, we preserve original duration.
            }
            
            updates.push({
                ...currentSegment,
                startDate: newStartDateStr,
                endDate: newEndDateStr,
            })
            
            previousEndDate = dayjs(newEndDateStr) // Use dayjs object for calculations
            
            // 2. Cascade changes to subsequent segments
            for (let i = segmentIndex + 1; i < segments.length; i++) {
                
                const nextSegment = segments[i]
                const durationDays = dayjs(nextSegment.endDate)
                    .diff(dayjs(nextSegment.startDate), 'day') // Preserve original duration
                
                const subsequentStartDate = previousEndDate
                const subsequentEndDate = subsequentStartDate.add(durationDays, 'day')
                
                updates.push({
                    ...nextSegment,
                    startDate: subsequentStartDate.toISOString(),
                    endDate: subsequentEndDate.toISOString(),
                })
                
                previousEndDate = subsequentEndDate // Update for the next iteration
                
            }
            
            // 3. Perform bulk update
            if (updates.length > 0)
                await segmentsRepo.table.bulkPut(updates)
            
        }) // End transaction
        
        toast('Segment dates updated')
        
    } catch (e) {
        
        console.error('Failed to update segment dates:', e)
        toast.error('Failed to update segment dates')
        
    }
    
}
